# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/default.xdc

# Block Designs: bd/FirstDraftBD/FirstDraftBD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD || ORIG_REF_NAME==FirstDraftBD} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_clk_wiz_0_1 || ORIG_REF_NAME==FirstDraftBD_clk_wiz_0_1} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_processing_system7_0_0/FirstDraftBD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_processing_system7_0_0 || ORIG_REF_NAME==FirstDraftBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_axi_gpio_0_0 || ORIG_REF_NAME==FirstDraftBD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_ps7_0_axi_periph_0/FirstDraftBD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_ps7_0_axi_periph_0 || ORIG_REF_NAME==FirstDraftBD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_rst_clk_wiz_0_100M_0/FirstDraftBD_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==FirstDraftBD_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_TopLevelLockin_opo_0_0/FirstDraftBD_TopLevelLockin_opo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_TopLevelLockin_opo_0_0 || ORIG_REF_NAME==FirstDraftBD_TopLevelLockin_opo_0_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/FirstDraftBD_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_system_ila_0_0 || ORIG_REF_NAME==FirstDraftBD_system_ila_0_0} -quiet] -quiet

# IP: bd/FirstDraftBD/ip/FirstDraftBD_auto_pc_0/FirstDraftBD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FirstDraftBD_auto_pc_0 || ORIG_REF_NAME==FirstDraftBD_auto_pc_0} -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/FirstDraftBD_ooc.xdc
