# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_auto_pc_0/FirstDraftBD_auto_pc_0.xci
# IP: The module: 'FirstDraftBD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_auto_pc_0/FirstDraftBD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_auto_pc_0/FirstDraftBD_auto_pc_0.xci
# IP: The module: 'FirstDraftBD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_auto_pc_0/FirstDraftBD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
