# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1.xci
# IP: The module: 'FirstDraftBD_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1.xci
# IP: The module: 'FirstDraftBD_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_clk_wiz_0_1/FirstDraftBD_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
