# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/FirstDraftBD_system_ila_0_0.xci
# IP: The module: 'FirstDraftBD_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/bd_0894.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0894 || ORIG_REF_NAME==bd_0894} -quiet] -quiet

# IP: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/bd_0894_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/bd_0894_ila_lib_0_ooc.xdc

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/bd_0894_ooc.xdc

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/FirstDraftBD_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/FirstDraftBD_system_ila_0_0.xci
# IP: The module: 'FirstDraftBD_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/bd_0894.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0894 || ORIG_REF_NAME==bd_0894} -quiet] -quiet

# IP: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/bd_0894_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0894_ila_lib_0 || ORIG_REF_NAME==bd_0894_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/ip/ip_0/bd_0894_ila_lib_0_ooc.xdc

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/bd_0/bd_0894_ooc.xdc

# XDC: d:/repos/red_pitaya_opo_locking/updated_RePLIA_vivado_project/VivadoProject/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_system_ila_0_0/FirstDraftBD_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
