# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0.xci
# IP: The module: 'FirstDraftBD_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.srcs/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0.xci
# IP: The module: 'FirstDraftBD_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chawlani/Lock_In_Red_pitaya/Lock_In_Red_pitaya.gen/sources_1/bd/FirstDraftBD/ip/FirstDraftBD_axi_gpio_0_0/FirstDraftBD_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FirstDraftBD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
